#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sino.Droid.SlidePager.Resource", IsApplication=false)]

namespace Sino.Droid.SlidePager
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int indicator_spacing = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int indicator_type = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int circle_indicator_solid = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int circle_indicator_stroke = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int fraction_indicator_bg = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public static int circle = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int fraction = 2130968577;
			
			// aapt resource value: 0x7f040003
			public static int indicator = 2130968579;
			
			// aapt resource value: 0x7f040002
			public static int pager = 2130968578;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int sino_droid_slidepager_slideview = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PageIndicator = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public static int PageIndicator_indicator_spacing = 0;
			
			// aapt resource value: 1
			public static int PageIndicator_indicator_type = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
